# Generated by Django 2.2.10 on 2020-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='has_header',
            field=models.BooleanField(default=False),
        ),
    ]
